### ISSUE TITLE
enable/disable light on gotway(begode) works not correct

### ISSUE THREAD

**Issue by paymicro** [Wheellog/Wheellog.Android#102]
Приложение "забывает" что свет уже включен через 30+ минут и пытается включить еще раз

**Comment by palachzzz** [comment]
странно почему оно забывает, должно бы в префы сохранится

**Comment by paymicro** [comment]
хех... Никуда не сохраняется =)
https://github.com/Wheellog/Wheellog.Android/blob/7b11c5b97963ff3f2ba81d53026fa50f74d3686d/app/src/main/java/com/cooper/wheellog/utils/GotwayAdapter.java#L94-L96

**Comment by paymicro** [comment]
Ну если инфа новая появится то переоткроем
