### ISSUE TITLE
kingsong serial is 0x63

### ISSUE THREAD

**Issue by enaon** [Wheellog/Wheellog.Android#129]
there is mistake in the description, not that in makes difference since you send all, but if one wants to monitor what he sends, then 
serial is 0x63
and model is 0x9B

thanks for the work done.

**Comment by paymicro** [comment]
are you talking about it?https://github.com/Wheellog/Wheellog.Android/blob/0e99fb8d01f43e18235e7fbaf3b5c49952d2e134/app/src/main/java/com/cooper/wheellog/utils/KingsongAdapter.java#L126-L131
If you are really sure of a mistake, could you do a PR?

**Comment by enaon** [comment]
I am not sure what a pr is, but yes I am sure about the byte reported. 

To send a serial request, I need to send to 0x63, I am doing extra checks for ks s18 so that it wont beep with no reason and stumbled on it. 

https://github.com/enaon/eucWatch/blob/main/P8-testing/eucKingsong/eucKingsong.js

**Comment by paymicro** [comment]
Ok. I understood you. This fix will be part of this PR of refactoring https://github.com/Wheellog/Wheellog.Android/pull/94
In commit https://github.com/Wheellog/Wheellog.Android/pull/94/commits/3d2302dd4a7de6ba7162fd4fef38c57e1ef9085c

**Comment by enaon** [comment]
nice, thank you.
