### ISSUE TITLE
Distance reported is inaccurate

### ISSUE THREAD

**Issue by bobpaul** [Wheellog/Wheellog.Android#156]
On my mten3 I think the speed is accurate (it seems the same as EUC World reports, at least), but the distance reported is quite far off. When I turn the wheel on and it connects, the distance almost immediately jumps to 0.63mi, before I've even gotten on the wheel. I just did a ride of less than 1mile and when I got to my destination, Wheel Log showed a distance of 12.6mile

**Comment by bobpaul** [comment]
I've verified that I'm running v2.2.11 from the Google Playstore and this was not fixed correctly. It looks like the `Distance` parameter is correctly showing `distance` when set to metric, but when the app is set to mph, the parameter shows the same value as `Top Speed`.

![image](https://user-images.githubusercontent.com/90864/114236673-949d5a00-9947-11eb-9c6a-ac5b79909c6d.png)

![image](https://user-images.githubusercontent.com/90864/114236703-9cf59500-9947-11eb-8f58-26e31ef811c3.png)

**Comment by paymicro** [comment]
@bobpaul fix has not yet been released to the google play
