### ISSUE TITLE
MiBand Horizontal Option 

### ISSUE THREAD

**Issue by Somnius** [Wheellog/Wheellog.Android#160]
I'd like to test out if I can fit the MiBand in the top of my helmet.
Can you guys make it so that it has the option to display the wheel information horizontally instead of vertically?

**Comment by paymicro** [comment]
The text itself cannot be rotated.
Only decision
```
S M D P
p a s W
d x t M

1 2 2 5
0 1 4 3
```
But I do not think that this is exactly what is needed

**Comment by Zappelphilipp** [comment]
I do have a related question: I do not have a mi band yet but consider getting one so i am not knowing how the API work and what is possible to display and what not. I found the documentation (https://github.com/Wheellog/Wheellog.Android/wiki/EN:Work-with-Mi-Band) for the mi band integration but for me its not really clear to me if it would be possible to only display the actual speed in big digits. All I need is a speedometer function :)
as far as i understand all data is transmitted to the "Master for Mi Band" App which does then send the data to the Mi Band. Is that correct?

**Comment by paymicro** [comment]
@Zappelphilipp mi band can only read notifications from other apps. The font and text size cannot be changed. `Master for Mi Band` app can periodically send update of a notification. 
There are several templates for transmitted information:
https://github.com/Wheellog/Wheellog.Android/blob/716372c15a33b4a999c44624fc2c3d1ce321f496/app/src/main/res/values/strings.xml#L515-L518
If you are looking for a wearable companion, take a closer look at a supported smartwatch (Pebble, Samsung, Garmin).

**Comment by Zappelphilipp** [comment]
> @Zappelphilipp mi band can only read notifications from other apps. The font and text size cannot be changed. `Master for Mi Band` app can periodically send update of a notification.
> There are several templates for transmitted information:
> https://github.com/Wheellog/Wheellog.Android/blob/716372c15a33b4a999c44624fc2c3d1ce321f496/app/src/main/res/values/strings.xml#L515-L518
> 
> 
> If you are looking for a wearable companion, take a closer look at a [supported smartwatch](https://github.com/Wheellog/Wheellog.Android#smart-watch-applications) (Pebble, Samsung, Garmin).

Thank you! Thats a bummer :(
