### ISSUE TITLE
Lights from notification button doesn't work

### ISSUE THREAD

**Issue by MarcelBuian** [Wheellog/Wheellog.Android#163]
Tested on Gotway Begote RS C30 on Android. 
In wheel settings, however, I can turn the lights on or off without problems. So the issue is with the light from notification only. 
![Screenshot_20210407-090618](https://user-images.githubusercontent.com/3746903/113818564-9f59c280-9780-11eb-9828-f82d5508964b.jpg)

**Comment by paymicro** [comment]
@MarcelBuian can you check? [app-debug](https://github.com/Wheellog/Wheellog.Android/suites/2444290890/artifacts/52351081)

**Comment by MarcelBuian** [comment]
@paymicro Yep, the lights notification button works there.
Bug fixed.
