### ISSUE TITLE
Gotway MTen3 67v wrong battery level

### ISSUE THREAD

**Issue by aallye** [Wheellog/Wheellog.Android#166]
With fully charged MTen3 67v (67v is chosen in options) the app shows 90%ish battery charge level (with no load), when teating with EUC World (and selecting MTen3 67v profile) is shows 100%.
Please help to fix.

**Comment by palachzzz** [comment]
There is no such option: 64V. So.. Which Mten do you have? 84v or 67v? but in any case, it doesn't matter, please show screenshot of main page with fully charged Mten

**Comment by aallye** [comment]
![Screenshot_20210413-231908](https://user-images.githubusercontent.com/17852401/114649807-2e9a3500-9caf-11eb-96e5-df53286324d3.png)
![Screenshot_20210413-231900](https://user-images.githubusercontent.com/17852401/114649808-2f32cb80-9caf-11eb-9fa4-13fb148b5d30.png)
Hi, yeah, this is 67, sorry for confudion, please find sceenshots attached

**Comment by palachzzz** [comment]
Switch off this option

![1231231](https://user-images.githubusercontent.com/13967220/114767460-51405280-9d70-11eb-83c3-16dbd411f36a.png)

**Comment by aallye** [comment]
Thank you, works fine with this disabled, please close request.
