### ISSUE TITLE
Speed alarm crashes app

### ISSUE THREAD

**Issue by paymicro** [Wheellog/Wheellog.Android#208]
### Description
The speed alarm crashes app when the main view is active.

**Comment by bobpaul** [comment]
I've had the app crash while on the other views (summary, graph, and trips; haven't tested on events). 

I'm using "Altered Alarms" with v2.3.5. From my initial observations, the Advance Warn speed alarm does not cause the crash. I think on the main screen the PWM start immediately causes the crash, but on other screens it does not always crash. I will do more testing.
