### ISSUE TITLE
App is killed after some minutes of ride

### ISSUE THREAD

**Issue by jforatier** [Wheellog/Wheellog.Android#222]
### Description
When i launch app before a ride session then i put phone in my pocket. The app is killed after some minutes and the session stop logging.

### Steps to reproduce
1. Starting application (with auto log) - at 12:22:00
2. Go to home (with Notification running)
3. Ride (without any interaction with phone)
...
The app is killed 💀 Last log : 12:31:00 (9 minutes) - I ride for 1 hour
Note: I heard the 'disconnect' sound during the ride

### Expected behavior
App continue to work in background and write log into .csv.

### Smartphone model and android version
OnePlus A6003
Android version: 10 - Oreo 8.1.0

### EUC model
Inmotion V8

### Workaround
I tried WheelLog AJDM v6.5 application (wich is a fork of Wheellog) and the issue is not present. 

**👉 Maybe there is a flag to add to say system to no kill the app**

**Comment by ggoraa** [comment]
Please check what battery optimisation settings are assigned to WheelLog
It is possible because WheelLog dies because of battery optimisation settings

**Comment by jforatier** [comment]
I've made a ride without Battery Optimisation, and it works.
But maybe we can add some flag or optimisation to avoid this. This is the only app i have to disable optimisation.

**Comment by ggoraa** [comment]
As you see, WheelLog gets an update for notifying the user that battery optimisation is enabled :D

**Comment by jforatier** [comment]
Great ! Thanks for the fix, i'll give it a try
