### ISSUE TITLE
FAILURE_DURING_TRANSER error while connecting to garmin watch

### ISSUE THREAD

**Issue by caballarius** [Wheellog/Wheellog.Android#254]
### Description
WheelLog 2.3.9
Companion app 1.0.13

As soon as I click the watch icon in WheeLog I get a FAILURE_DURING_TRANSFER error message and get redirected the ConnectIQ website (not ConnectIQ app). There I get an additional error message:

"The WheeLog App used with this application is not installed on your ConnectIQ device. Please install the widget and try again". ConnectIQ site shows app as installed.

 Same error whether companion app is started or not.  

### Smartphone model and android version
Uniherz Jelly 2 - Android 10

### EUC model
Kingsong 14D

**Comment by ggoraa** [comment]
You use an old companion, WheelLog just redirected you to an app store page to download a new companion. Just download that companion, and your error will go away :D

**Comment by ggoraa** [comment]
https://apps.garmin.com/ru-UA/apps/35719a02-8a5d-46bc-b474-f26c54c4e045
Here is the link to a new app

**Comment by caballarius** [comment]
But there I get the error that it is not compatible with my Garmin Fenix 5X
![Screenshot_20210802-083814](https://user-images.githubusercontent.com/25002009/127815274-fd4dcfcc-ac16-4097-8b80-f6448ffc3041.png)

**Comment by ggoraa** [comment]
Oh, I get it now.
I forgot to specify fenix5x Plus as a supported device, I will release a new version in 10 minutes with support for fenix5xplus

**Comment by ggoraa** [comment]
Done! Released 2.3.10, now with fenix 5X Plus support!
