### ISSUE TITLE
Do not working with Mi Band 6 

### ISSUE THREAD

**Issue by ltertok** [Wheellog/Wheellog.Android#261]
### Description

https://github.com/Wheellog/Wheellog.Android/wiki/Work-with-Mi-Band

Following the procedure instructions for mi band and android and Master for Mi Band app,
I can not setup notification on Master for Mi Band app and . 
Interruptions intarface is not shown in this android OS version 

### Steps to reproduce

1. 
2. 
3. 

### Smartphone model and android version

Android version: 8.1.0

### EUC model

KS14d 

### Workaround
![WhatsApp Image 2021-08-02 at 11 52 49](https://user-images.githubusercontent.com/545476/127882290-18f77b69-e4b4-4e6b-adad-c150cec9b482.jpeg)
![WhatsApp Image 2021-08-02 at 11 52 59](https://user-images.githubusercontent.com/545476/127882309-e9bb6858-d130-4e43-baed-6b7b3a58888c.jpeg)

**Comment by ltertok** [comment]
I am available to collect logs and report the app's usability and manual tests, best regards.   email to LTERTOK@gmail.com
PS keep in mind that the screen is small and the front size is fundamental for a perfect visualization, especially of battery speed and temperature

**Comment by hawkadmin** [comment]
you need notify for miband 6. Master for mi band don't work with miband 6.

**Comment by ltertok** [comment]
> need notify for miband 6.

 I will try it. Best Regards

**Comment by ltertok** [comment]
> > need notify for miband 6.
> 
> I will try it. Best Regards

Hi Could you explain the setup? I believe this android version does not facilitate this interface with notifications and interruptions.

In fact this app [notify for miband ] is better and can talk to mifit, but I still haven't been able to make it listen to the [wheel log] app

**Comment by ltertok** [comment]
> > > need notify for miband 6.
> > 
> > 
> > I will try it. Best Regards
> 
> Hi Could you explain the setup? I believe this android version does not facilitate this interface with notifications and interruptions.
> 
> In fact this app [notify for miband ] is better and can talk to mifit, but I still haven't been able to make it listen to the [wheel log] app

![WhatsApp Image 2021-08-10 at 11 47 40](https://user-images.githubusercontent.com/545476/128891916-e4ef6bc0-007e-4b94-be44-fcd5c93b660e.jpeg)
![WhatsApp Image 2021-08-10 at 11 48 27](https://user-images.githubusercontent.com/545476/128891922-420f8478-c14d-4fbc-9054-d38002ceb6cd.jpeg)
![WhatsApp Image 2021-08-10 at 11 48 54](https://user-images.githubusercontent.com/545476/128891926-fd88dbc7-a077-414d-9268-c000e982eece.jpeg)

**Comment by ltertok** [comment]
https://github.com/Wheellog/Wheellog.Android/wiki/Work-with-Mi-Band
I tried to configure it in a similar way in the item applications + Wheelog details

**Comment by ltertok** [comment]
I found out that a peculiarity of the Samsung A1 android OS is that this disabled the possibility of application overlay, it is possible that this has been disabled due to the performance of the device.

**Comment by ltertok** [comment]
Similar to it https://www.youtube.com/watch?v=i_z7Laukp9M

**Comment by Sergioloid** [comment]
Hi, @ltertok have you found a way to make this work? Currently, it seems that the support is now native, it should work without any additional application, but trying this I've found out that it launches only a single notification, then it stops.
