### ISSUE TITLE
Ninebot Z6 doesn't connect anymore

### ISSUE THREAD

**Issue by Sergioloid** [Wheellog/Wheellog.Android#334]
### Description
When using the play store app attempting to connect to my Ninebot z6 (firmware 1.7.6.0) it doesn't connect, giving an error "Failed to direct connect to the wheel"
However, the Ninebot display shows the BT connection icon and also reproduces a sound as if it's connected.

As an additional hint, the app was working fine ~5month ago, with same wheel and same phone.
### Steps to reproduce
1. Open the app
2. Click on the BT icon (or use the 'self-connection option')
3. Select the Wheel from the BT list

### Expected behavior
That the wheel will be connected.

### Smartphone model and android version
OnePlus 7T. Android version: 11

### EUC model
Ninebot Z6 (modded firmware)

### Workaround
No usable workaround is found.

**Comment by osimmac** [comment]
Same on my z10, stock firmware v1.1.0.7, tried clearing data and cache, didn't help. The wheel will make the connect sound but wheel log shows no data.

**Comment by Sergioloid** [comment]
@osimmac I found a temporary workaround, using this version: https://github.com/Wheellog/Wheellog.Android/releases/tag/2.4.7 everything seems to work.

**Comment by Sergioloid** [comment]
The issue was solved with the last update (2.5.5) Thanks!!
