### ISSUE TITLE
new Dialog when PWM is not set.

### ISSUE THREAD

**Issue by paymicro** [Wheellog/Wheellog.Android#343]
**Describe the solution you'd like**
При подключении нового колеса (необязательно нового, главное что с ненастроенными скоростью и напряжением раскрутки), выводится окно:
Для корректного отображения pwm нужно ввести скорость и напряжение раскрутки. И тут три варианта:
1. Ввести вручную (и там два ползунка скорость и напряжение раскрутки)
2. Рассчитать автоматически (после нажатия надо будет раскрутить и автоматом ввести полученные цифры)
3. Выбрать из предзаполненных - выберите модель колеса

Такое меню не нужно выводить для колес с аппаратным pwm, это все кингсонги, инмо в11 с версией выше 1.4 (там есть в адаптере версия), инмо В12, и ветераны с версией прошивки 2.х.х и выше

**Comment by alex13sh** [comment]
А как настроить PWM, когда диалоговое окно не высвечивается? Может при первом подключении я его скипнул и не заметил. Но сейчас вилог выдаёт некорректный шим. 
Может это от колеса зависит? У меня бигуди херо

**Comment by palachzzz** [comment]
Настройки -> Предупреждения-> 
* Включить предупреждения 
* Включить Альтернативные предупреждения
* Настроить скорость и напряжение раскрутки
После этого можно выключить предупреждения, если они не нужны
