### ISSUE TITLE
inmotion v12: abnormal voltage sag when wheel is shutting down

### ISSUE THREAD

**Issue by pokanoka** [Wheellog/Wheellog.Android#345]
When wheel is shutting down (actually shutting down normally, e.g. after 10 minutes with screen off), it reports abnormally low voltage values, which wheellog then remembers as voltage sag, overwriting previous - meaningful - voltage sag value.
Reported voltage values are on the order of 12v, 13v, or the like.
I believe workaround should be implemented: if voltage rapidly drops to lower than 24v (1v per cell), voltage sag recorded in the preceeding 3 seconds should be discarded and it's previous value restored.

wheel: v12 ht, firmware 1.6.12
wheellog version: 2.5.5

**Comment by palachzzz** [comment]
We can think about voltage sag, but I don't see any way to keep usual "voltage" to be relevant to the last metric. 
BTW, what is the need to see last voltage? You can check battery percentage, because for V11/V12 it is not related to Voltage, and will show correct data even during shutdown

**Comment by palachzzz** [comment]
Well, as you told = voltage value it the absolute truth. So during power off, BMS disconnect controller from power, so controller measures absolute truth - he is loosing voltage, working some time using capacitors.
If I implement some workaround to voltage, it will become to not to be truth.
