### ISSUE TITLE
Picture-in-picture support

### ISSUE THREAD

**Issue by gowgos5** [Wheellog/Wheellog.Android#388]
PiP window can display current speed, distance, and battery level.

**Comment by paymicro** [comment]
something like that?
![h](https://user-images.githubusercontent.com/27482193/211434299-d1d0dd7b-aa7d-4753-96e8-be8c3bd3d16b.gif)

**Comment by gowgos5** [comment]
Thanks! This looks really good! Could it be of a smaller size (roughly that of video playback from, say, Youtube) though? I reckon only important specs such as current speed and battery level need to be displayed in that window.

**Comment by paymicro** [comment]
This is on virtual Android 13. On a real device, the window is much smaller. I can only set its proportions.
The text is not very readable in such a window, so I need to make a special design for it with icons.
