### ISSUE TITLE
More than one device support

### ISSUE THREAD

**Issue by iwanko** [Wheellog/Wheellog.Android#442]
Is there a possibility of some sort of official support for several EUCs on a single phone?

Even an "official" duplicate apk that can work in parallel with the original one will do. I tried making a copy, but it won't connect to the wheel properly, probably because of some conflicts with data storage.

**Comment by paymicro** [comment]
Official support can only be provided by official manufacturers. We are not connected in any way with the official EUCs manufacturers.

And what do you mean by supporting several EUCs? Wheellog supports connecting to different EUCs on a single phone.

**Comment by iwanko** [comment]
Oops, my bad, I've read somewhere than connecting several EUCs in one app leads to unexpected behaviour, so I didn't even risk trying it (just in case). Maybe this was old news; anyways thanks.
