### ISSUE TITLE
Failed to open map list is empty

### ISSUE THREAD

**Issue by Omer78130** [Wheellog/Wheellog.Android#476]
### Description
Trip log file size is 0 kb and map opens with error message "Failed to open map list is empty"

I think it happens since I got last Samsung update with Android 14

### Steps to reproduce

1. Open wheellog
2. Ride for some time
3. Upload trip log
4. Slide to trip list 
5. View map

### Expected behavior

It is expected to show map with start end finish points.

### Smartphone model and android version
S22 Ultra, Android 14, One UI 6

### EUC model

KS 14S

**Comment by Omer78130** [comment]
![0 kb file](https://github.com/Wheellog/Wheellog.Android/assets/43449155/2ab79631-bc99-4195-94b3-f9bb07592dd9)
![Error_upload](https://github.com/Wheellog/Wheellog.Android/assets/43449155/7bfc7e67-8e6b-490c-ae9e-43a643556b02)
![Failed to open map](https://github.com/Wheellog/Wheellog.Android/assets/43449155/cb6a96d9-7b01-4ffc-84c5-8d6d9f7bb07d)

3 Screen captures: error at uploading, file list with 0 kb files, failed to open map.

**Comment by paymicro** [comment]
Hi @Omer78130 
Can you test the debug version? - https://github.com/Wheellog/Wheellog.Android/actions/runs/7426228819/artifacts/1150818087

**Comment by Omer78130** [comment]
Hi @paymicro 

Thank you for your assistance.
I tested the debug version and it works: my trips are logged, although gps locations are not very accurate,
Tell me if you need me to share any log files.

**Comment by EUC-Rider** [comment]
The solution to this problem is that the Log needs to be written to the memory of your phone. This is caused by insufficient write access permissions on the phone. You can try to open the APP authorization management and grant the storage write permission to the APP. This should solve your problem. Question, give it a try!

**Comment by Omer78130** [comment]
Hi @EUC-Rider.
I find no missing or refused authorization for Wheelog. I compared Wheelog and Whelog Debug and they use same authorization.
Also please not, that files are written in logs folder but their size is 202 o with only header line.
