### ISSUE TITLE
New version 3.13 PWM calculation error(Veteran Sherman)

### ISSUE THREAD

**Issue by EUC-Rider** [Wheellog/Wheellog.Android#483]
### Description

When running the new version 3.13 on Sherman models,PWM There will be an error in the calculation, the speed is only 40 kilometers per hour.PWM The display shows that the output is more than 140%, which is unreasonable; in version 3.11, the speed is 40 kilometers per hour PWM Falling around 60%; currently cannot be adjusted from any wheel settings.
### Steps to reproduce

1. The main screen displays PWM Display value
2. 
3. 

### Screenshots

![Screenshot_2024-03-09-16-28-23-574_com cooper wheellog-edit](https://github.com/Wheellog/Wheellog.Android/assets/115446617/3b6f0ea8-dcf9-49d9-a22c-a32d72a06398)

### Smartphone model and android version

XiaoMi Poco F5
### EUC model

Veteran Sherman

### Workaround

Currently you can only remove the new version (3.13) and install back to the old version (3.11)

**Comment by palachzzz** [comment]
You need to configure Rotation Speed and Rotation Voltage in Alarm settings

**Comment by EUC-Rider** [comment]
> 您需要在警報設定中配置轉速和旋轉電壓

Okay, since the preset alarm function is off, I tried turning it on and adjusting the voltage to try.
