### ISSUE TITLE
Triggerable Noises/Speech

### ISSUE THREAD

**Issue by Erudition** [Wheellog/Wheellog.Android#489]
**Is your feature request related to a problem? Please describe.**
I don't look at my screen when riding. Occasionally I'll look at my swartwatch, but otherwise I mostly rely on EUC world for occasional announcements over a bluetooth headset. Those are using TTS, but even simple noises would work.

**Describe the solution you'd like**
Ability to set a sound to play in situations like:
- Connected
- Started recording
- Speed reached setpoint
- Safety Margin reached setpoint
- Low battery
- Very Low Battery

And a stats readout every [distance] or so

**Describe alternatives you've considered**
Strapping my phone to my chest

**Additional context**
Feature exists in EUC world. Would love to use Wheellog full time.

**Comment by palachzzz** [comment]
We will not add speach feature in Wheellog
