### ISSUE TITLE
Android 13 version will cause the WheelLog App itself to be unable to set "access permissions", causing the track recording to fail.

### ISSUE THREAD

**Issue by EUC-Rider** [Wheellog/Wheellog.Android#494]
### Description

Android 13 version will cause the WheelLog App itself to be unable to set "access permissions", causing the track recording to fail.

### Steps to reproduce

1. Turn on application authorization
2. Click to grant permission items
3. Unable to see authorization items for "Access Storage"
4. The APP access function must be modified so that it can actually be displayed in the Andoird 13 application authorization function (currently, the authorization of any "access" item cannot be displayed)

### Smartphone model and android version

Android 13

### EUC model

All wheels are the same

### Workaround

There is no solution. I can only wait for the author to update the APP authorization project to comply with Android 13 settings.

**Comment by palachzzz** [comment]
> Unable to see authorization items for "Access Storage"
It is not needed to have this permission to write logs, and read logs which is stored by Wheellog. 
Access Storage providing too much access to the files, that's why it is not allowed to use it to usual applications

**Comment by EUC-Rider** [comment]
After repeated testing, we found that the "location" authorization method will cause the "View Maps" function to fail; the "file" information that has been written cannot be read normally, and the "simple summary" file information cannot be displayed normally in the record. .

Solution: Android users must "Always allow" WheelLog for location access rights. Please do not select "Allow location access only when using APP". This will lead to this result.
![Screenshot_2024-05-28-10-07-27-611_com cooper wheellog-edit](https://github.com/Wheellog/Wheellog.Android/assets/115446617/8a0c9f33-98e8-4725-892f-22dc53f0d143)
![Screenshot_2024-05-28-10-07-39-994_com cooper wheellog-edit](https://github.com/Wheellog/Wheellog.Android/assets/115446617/eb6e4684-fd4f-4784-9ef0-eeceb8d62a1d)

**Comment by palachzzz** [comment]
That's correct, Wheellog can show map, if there is no location data.
But Wheellog can't push user to use GPS location, as it violates Google policy.
