### ISSUE TITLE
Значение смайликов

### ISSUE THREAD

**Issue by n-osennij** [Wheellog/Wheellog.Android#495]
Добрый день. Подскажите, какое именно значение скрыто за смайликами, что они означают?

![2024-05-21 22 50 29](https://github.com/Wheellog/Wheellog.Android/assets/17576299/5c39b902-111d-48cd-aee5-66227a2e3d84)

Вот, как это понимаю я:
- ракета - максимальная скорость.
- тарелка - наверное, средняя (или медианная) скорость по gps? или не средняя скорость?
- человек на коляске - минимальная скорость?
- ужасающийся смайлик - нет идей, что это такое...
- часы - время поездки
- линейка - преодоленное расстояние
- молния - подозреваю, что это кол-во электроэнергии, затраченной на поездку
- батарейка - возможно, средний (или медианный?) расход электроэнергии на километр.

нигде не нашел информации по этому поводу.

**Comment by paymicro** [comment]
https://t.me/wheellog/35628

**Comment by palachzzz** [comment]
Создал страницу на Wiki
https://github.com/Wheellog/Wheellog.Android/wiki/%D0%98%D0%BA%D0%BE%D0%BD%D0%BA%D0%B8-%D0%BD%D0%B0-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B5-%D0%BF%D0%BE%D0%B5%D0%B7%D0%B4%D0%BE%D0%BA

Eng:
https://github.com/Wheellog/Wheellog.Android/wiki/Trip-page-icons
